---
title: "Analisis de activo fianciero (BOLSAA)"
author: "Iván Arellano , Juan Pablo Rodriguez , Santiago"
date: "31/8/2021"
output: html_document
---


## **Introducción:**
<p style='text-align: justify;'>
En este proyecto, analizamos a la Bolsa Mexicana de Valores como activo financiero, en esta primera entrega describiremos un poco de lo que va la empresa, su información relevante para informar ampliamente y que le pueda ser de utilidad a un posible inversionista, sus rendimientos históricos desde el 2019 hasta la fecha (trimestralmente). Además hablaremos sobre los riesgos que conlleva esta empresa, entre otras características de este activo.
</p>


## **Bolsa Mexicana de valores**
<p style='text-align: justify;'>
La [Bolsa Mexicana de Valores SAB de CV](https://www.bmv.com.mx/es/Grupo_BMV') opera como una empresa de servicios financieros. La empresa se dedica al comercio de efectivo, derivados cotizados y mercados extrabursátiles para múltiples clases de activos. Ofrece cotización, negociación y operaciones de instrumentos de renta variable y deuda cotizados y servicios de custodia, compensación, liquidación, contraparte y venta de datos. La empresa fue fundada en 1894 y tiene su sede en la Ciudad de México, México.
</p>


## **Información relevante del activo:** 

- Clave de pizarra:  **(BOLSA A)**
- Inicio de cotización:  **13 de Junio 2008 realiza su oferta pública en la BMV**
- Número de acciones en el mercado: **590,139,742**
- Precio actual: **40.600** (Precio al 27 de Agosto del 2021) 
- P.E.R.(Price/earnings ratio): **17.15**
- Cap Mercado: **23.96B**
- Fecha próximos resultados: **30 agosto 2021**
- Número de empleados: **534**
- Dividendos: **2.02 por acción** 
- Oficinas centrales: **Ciudad de México, PASEO DE LA REFORMA 255 CUAUHTEMOC ,06500, MEXICO CDMX.**


<sup> Datos recopilados de [GBM+](https://plus.gbm.com/index.html),[Investing]('https://www.investing.com/equities/bolsa-mexicana-de-valores-a') y [Factset](https://login.factset.com/login/xoM4jTODNt1DQZiEFfv2epjgwEy_90OY4PMHmCT4nVWBNoOUq5l1gngk-6goz21COdbrZuVD15k0pCIYD-6IuetP5fqblSARR2M8A421ykG2qY2giA_YLQ/xoM55/Qxo97)  <sup>


## Rendimiento Acumulado

| Año actual |<font color = red>   -13.91%  |
|:----------:|:----------------------------:|
| 1 mes      | <font color = red>   -1.65%  |
| 3 Años     | <font color = green>  6.73%  |
| 5 Años     | <font color = green> 18.20%  |






